---
# tasks file for gitlab
#
- name: Install required packages
  include_tasks: install_packages.yml

- name: Add Gitlab repo task
  include_tasks: add_gitlab_repo.yml

- name: Basic configuration
  include_tasks: post_install_config.yml
